### ISSUE TITLE
Text warp in Kusama slot page

### ISSUE THREAD

**Issue by Keotto-boll** [airalab/robonomics.network#101]
<img width="783" alt="Снимок экрана 2022-11-14 в 14 29 56" src="https://user-images.githubusercontent.com/116081111/201702325-dc61e6f2-e30e-4ee8-b41b-e52fda04d646.png">

Second string, last word. 
Mac os, 1440x900, Chrome.

**Comment by Keotto-boll** [comment]
https://robonomics.network/ru/kusama-slot/

**Comment by positivecrash** [comment]
fixed
