### ISSUE TITLE
New XRT distribution release March 2021

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics.network#20]
Pls change the link on the token page to https://ipfs.io/ipfs/QmejC5QaG6LxPJz7EQ8XuKuCuWqg9oq3NBL93SRqsqkKKv

**Comment by ensrationis** [comment]
New link: https://ipfs.io/ipfs/QmYjv65UNTM3F7LFR1ESm5CVMLWYLagwtT7qGAsaBi47nY/releases_March'21_4v.pdf @positivecrash

**Comment by positivecrash** [comment]
done
