### ISSUE TITLE
XRT balances not showing in Polkadot.js Portal

### ISSUE THREAD

**Issue by banatarski** [airalab/robonomics.network#33]
XRT balances on Robonomics Parachain only showing pre-exodus/genesis balances.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.rpc.robonomics.network%2F#/accounts

Checking https://robonomics.subscan.io/ shows correct balances for everyone.

**Comment by ensrationis** [comment]
Yes, that is the result of preparations for 2nd Robonomics Crowdloan campaign. We need to have genesis state of parachain before deployment of crowdloan module, and in the same time we continue support Frontier network development. Parallel universes its a hard :) 

All Plan "B"  balances will be injected several weeks after the Kusama parachain launch.

Correct balances can found here too: https://parachain.robonomics.network/?rpc=wss%3A%2F%2Fmain.frontier.rpc.robonomics.network%2F#/accounts

**Comment by banatarski** [comment]
Noted, thanks for the answer!
