### ISSUE TITLE
Invalid link on coingecko

### ISSUE THREAD

**Issue by Leemo94** [airalab/robonomics.network#35]
On the $XRT coingecko page, the robonomics.network link directs the user to a 404'd URL (https://robonomics.network/en/).
This is just because of the en/ at the end of the URL.
It is of course quite easy to go from this page to the main site, but it confuses some users.

Perhaps we can make that URL redirect to the valid site homepage? It's probably easier / quicker than contacting coingecko?

**Comment by Leemo94** [comment]
The same issue exists on Etherscan: https://etherscan.io/token/0x7de91b204c1c737bcee6f000aaa6569cf7061cb7

**Comment by positivecrash** [comment]
robonomics.network is serverless website, gh-pages hosted. So unfortunately we don't have possibility redirect pages now

**Comment by positivecrash** [comment]
Fixed
