### ISSUE TITLE
Navigation panel in DAPP doesn't collapse after changing the section

### ISSUE THREAD

**Issue by arseniiarsenii** [airalab/robonomics.network#85]
Navigation panel in DAPP doesn't collapse after changing the section.

See screencast attached.

Firefox mobile on Android 12.
https://user-images.githubusercontent.com/74658894/193881467-12c00af5-f590-45ad-b7be-a417f5c2834e.mp4

**Comment by tubleronchik** [comment]
Faced the same problem on Safari mobile iOS 15.4.
The screencast is attached below. 
https://user-images.githubusercontent.com/36592446/193882250-2f36c5e1-5eec-4b5e-938f-1547d8236f38.MOV

**Comment by positivecrash** [comment]
https://github.com/airalab/dapp.robonomics.network/issues - ford dapp issues
