### ISSUE TITLE
Add Robonomics Keypoint presentation in Community / Docs section 

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics.network#9]
title: 
Robonomics Keypoint, updated August'2020

Desc: 
Keypoint presentation of Robonomics project. Brief and direct. Consist of: executive summary, main definitions, project history timeline, and many useful links in the text. 

Strongly recommend sharing with your friends, colleagues, and subscribers to let them know more about Robonomics.network

Presentation attached:
[Robonomics Keypoint, updated August'2020.pdf](https://github.com/airalab/robonomics.network/files/5061595/Robonomics.Keypoint.updated.August.2020.pdf)

**Comment by positivecrash** [comment]
added. check here: https://robonomics.network/community/#docs
